default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: rootpw
  host: 127.0.0.1

development:
  <<: *default
  database: jobs_development

test:
  <<: *default
  database: jobs_test

production:
  url: <%= ENV['DATABASE_URL'] %>
